server:
   port: 80
   
spring:
   datasource:
     url: jdbc:mysql://127.0.0.1/C81-S3-Lwc-blog?useUnicode=true&characterEncoding=UTF-8
     username: root
     password: 
     driver-class-name: com.mysql.jdbc.Driver 
     
logging:
   level: 
        com.yc.S3Lwcblog.dao: debug